version: '3.8'

services:
  kef-control-panel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./data/:/var/www/html/data/
    restart: always
